# Generated by Django 5.0.8 on 2024-08-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions_data", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
