# Generated by Django 5.0.8 on 2024-08-09 11:51
import os

from django.db import migrations, models


def populate_user_data(apps, schema_editor):
    User = apps.get_model("actions_data", "User")
    api_token = os.environ.get("ACTIONS_INSIDER_API_TOKEN", "")
    User.objects.create(
        id=1679647,
        login="eduramirezh",
        avatar_url="https://avatars.githubusercontent.com/u/1679647?v=4",
        api_token=api_token,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("actions_data", "0002_alter_organization_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("login", models.CharField(max_length=100)),
                ("avatar_url", models.URLField()),
                ("api_token", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="organization",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="updated_at",
        ),
        migrations.RunPython(populate_user_data),
    ]
