# Generated by Django 5.0.8 on 2024-08-12 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions_data", "0003_user_remove_organization_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PullRequest",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("number", models.IntegerField(null=True)),
                ("url", models.URLField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="workflowrun",
            name="actor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workflows_as_actor",
                to="actions_data.user",
            ),
        ),
        migrations.AddField(
            model_name="workflowrun",
            name="artifacts_url",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="workflowrun",
            name="cancel_url",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="workflowrun",
            name="check_suite_id",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="workflowrun",
            name="check_suite_node_id",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="workflowrun",
            name="check_suite_url",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="workflowrun",
            name="display_title",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="workflowrun",
            name="event",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="workflowrun",
            name="head_branch",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="workflowrun",
            name="head_commit",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="workflowrun",
            name="head_repository",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workflows_as_head_repository",
                to="actions_data.repository",
            ),
        ),
        migrations.AddField(
            model_name="workflowrun",
            name="head_sha",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="workflowrun",
            name="html_url",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="workflowrun",
            name="jobs_url",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="workflowrun",
            name="logs_url",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="workflowrun",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="workflowrun",
            name="node_id",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="workflowrun",
            name="path",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="workflowrun",
            name="previous_attempt_url",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="workflowrun",
            name="referenced_workflows",
            field=models.ManyToManyField(
                related_name="workflows_were_referenced", to="actions_data.workflow"
            ),
        ),
        migrations.AddField(
            model_name="workflowrun",
            name="rerun_url",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="workflowrun",
            name="run_attempt",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="workflowrun",
            name="run_number",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="workflowrun",
            name="run_started_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="workflowrun",
            name="triggering_actor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workflows_as_triggering_actor",
                to="actions_data.user",
            ),
        ),
        migrations.AddField(
            model_name="workflowrun",
            name="url",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="workflowrun",
            name="workflow_url",
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar_url",
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="html_url",
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="url",
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name="workflowrun",
            name="conclusion",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="workflowrun",
            name="created_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="workflowrun",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="workflowrun",
            name="repository",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workflows_as_repository",
                to="actions_data.repository",
            ),
        ),
        migrations.AlterField(
            model_name="workflowrun",
            name="status",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="workflowrun",
            name="updated_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="workflowrun",
            name="workflow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workflow_runs",
                to="actions_data.workflow",
            ),
        ),
        migrations.AddField(
            model_name="workflowrun",
            name="pull_requests",
            field=models.ManyToManyField(to="actions_data.pullrequest"),
        ),
    ]
