# Generated by Django 5.0.8 on 2024-08-12 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions_data", "0004_pullrequest_workflowrun_actor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="repositories",
                to="actions_data.user",
            ),
        ),
    ]
