# Generated by Django 5.0.8 on 2024-08-12 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions_data", "0005_repository_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="OwnerEntity",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("login", models.CharField(max_length=100)),
                ("avatar_url", models.URLField(null=True)),
                ("api_token", models.CharField(max_length=100)),
                (
                    "entity_type",
                    models.CharField(
                        choices=[("User", "User"), ("Organization", "Organization")],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="repository",
            name="organization",
        ),
        migrations.AlterField(
            model_name="repository",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="repositories",
                to="actions_data.ownerentity",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="workflowrun",
            name="actor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workflows_as_actor",
                to="actions_data.ownerentity",
            ),
        ),
        migrations.AlterField(
            model_name="workflowrun",
            name="triggering_actor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workflows_as_triggering_actor",
                to="actions_data.ownerentity",
            ),
        ),
        migrations.DeleteModel(
            name="Organization",
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
