# Generated by Django 5.0.8 on 2024-08-12 14:35

import os

from dotenv import load_dotenv
from django.db import migrations


load_dotenv()


def populate_user_data(apps, schema_editor):
    OwnerEntity = apps.get_model("actions_data", "OwnerEntity")
    api_token = os.environ.get("ACTIONS_INSIDER_API_TOKEN", "")
    OwnerEntity.objects.create(
        id=1679647,
        login="eduramirezh",
        avatar_url="https://avatars.githubusercontent.com/u/1679647?v=4",
        api_token=api_token,
        entity_type="User",
    )


class Migration(migrations.Migration):
    dependencies = [
        ("actions_data", "0006_ownerentity_remove_repository_organization_and_more"),
    ]

    operations = [
        migrations.RunPython(populate_user_data),
    ]
