# Generated by Django 5.0.8 on 2024-08-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions_data", "0007_auto_20240812_1435"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="check_run_url",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="completed_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="html_url",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="labels",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="node_id",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="runner_group_id",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="runner_group_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="runner_id",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="runner_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="started_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="steps",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="url",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="workflowrun",
            name="run_id",
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="job",
            name="created_at",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="job",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="workflowrun",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddConstraint(
            model_name="workflowrun",
            constraint=models.UniqueConstraint(
                fields=("run_id", "run_attempt"), name="unique_run_attempt"
            ),
        ),
    ]
