# Generated by Django 5.0.8 on 2024-08-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "actions_data",
            "0008_job_check_run_url_job_completed_at_job_html_url_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="workflow_run",
        ),
        migrations.AddField(
            model_name="job",
            name="workflow_run_attempt",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="workflow_run_id",
            field=models.IntegerField(),
            preserve_default=False,
        ),
    ]
