# Generated by Django 5.0.8 on 2024-08-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "actions_data",
            "0009_remove_job_workflow_run_job_workflow_run_attempt_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="ownerentity",
            name="api_token",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
