# Generated by Django 5.0.8 on 2024-08-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions_data", "0010_alter_ownerentity_api_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ownerentity",
            name="api_token",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
