# Generated by Django 5.0.8 on 2024-08-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions_data", "0011_alter_ownerentity_api_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="Billing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_minutes_used", models.IntegerField()),
                ("total_paid_minutes_used", models.IntegerField()),
                ("included_minutes", models.IntegerField()),
                ("minutes_used_breakdown", models.JSONField()),
            ],
        ),
    ]
