# Generated by Django 5.1 on 2024-08-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions_data", "0012_billing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflow",
            name="node_id",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
