# Generated by Django 5.1 on 2024-08-16 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions_data", "0013_alter_workflow_node_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="workflow_run_attempt",
        ),
        migrations.RemoveField(
            model_name="job",
            name="workflow_run_id",
        ),
        migrations.AddField(
            model_name="job",
            name="workflow_run",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="actions_data.workflowrun",
            ),
            preserve_default=False,
        ),
    ]
