# Generated by Django 5.1 on 2024-09-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions_data", "0017_ownerentity_webhook_enabled"),
        ("social_django", "0016_alter_usersocialauth_extra_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="allowed_access",
            field=models.ManyToManyField(
                related_name="allowed_repositories", to="social_django.usersocialauth"
            ),
        ),
    ]
