# Generated by Django 5.1 on 2024-09-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions_data", "0018_repository_allowed_access"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payload", models.JSONField()),
                ("delivery", models.CharField(max_length=255)),
                ("event", models.CharField(max_length=255)),
                ("hook_id", models.IntegerField()),
                ("hook_installation_target_id", models.IntegerField()),
                ("hook_installation_target_type", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
