# Generated by Django 5.1 on 2024-09-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions_data", "0019_webhookevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowrun",
            name="webhook_events",
            field=models.ManyToManyField(to="actions_data.webhookevent"),
        ),
        migrations.AlterField(
            model_name="workflowrun",
            name="run_id",
            field=models.PositiveBigIntegerField(),
        ),
    ]
