# Generated by Django 5.1 on 2024-09-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions_data", "0020_workflowrun_webhook_events_alter_workflowrun_run_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflowrun",
            name="check_suite_id",
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
