# Generated by Django 5.1 on 2024-09-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions_data", "0021_alter_workflowrun_check_suite_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhookevent",
            name="processed_at",
            field=models.DateTimeField(null=True),
        ),
    ]
