# Generated by Django 5.1 on 2024-09-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions_data", "0022_webhookevent_processed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="webhook_events",
            field=models.ManyToManyField(to="actions_data.webhookevent"),
        ),
        migrations.AlterField(
            model_name="job",
            name="id",
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False),
        ),
    ]
