# Generated by Django 5.1 on 2024-09-18 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions_data", "0023_job_webhook_events_alter_job_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="workflow_run",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="actions_data.workflowrun",
            ),
        ),
    ]
