# Generated by Django 5.1 on 2024-09-18 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions_data", "0024_alter_job_workflow_run"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflowrun",
            name="workflow",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workflow_runs",
                to="actions_data.workflow",
            ),
        ),
    ]
