# Generated by Django 5.1 on 2024-09-24 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions_data", "0025_alter_workflowrun_workflow"),
        ("social_django", "0016_alter_usersocialauth_extra_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="RepositoryAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("GITHUB_API", "Github API"),
                            ("MANUAL", "Manual"),
                        ],
                        default="GITHUB_API",
                        max_length=50,
                    ),
                ),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="actions_data.repository",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="social_django.usersocialauth",
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "repository")},
            },
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="repository",
                    name="allowed_access",
                    field=models.ManyToManyField(
                        related_name="allowed_repositories",
                        through="actions_data.RepositoryAccess",
                        to="social_django.usersocialauth",
                    ),
                ),
            ],
        ),
    ]
