# Generated by Django 5.1 on 2024-09-30 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions_data", "0026_repositoryaccess_alter_repository_allowed_access"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="name",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="job",
            name="node_id",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="runner_group_name",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="runner_name",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="workflowrun",
            name="check_suite_node_id",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="workflowrun",
            name="display_title",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="workflowrun",
            name="head_branch",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="workflowrun",
            name="head_commit",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="workflowrun",
            name="head_sha",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="workflowrun",
            name="name",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="workflowrun",
            name="node_id",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="workflowrun",
            name="path",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
