# Generated by Django 5.1 on 2024-09-30 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("actions_data", "0027_alter_job_name_alter_job_node_id_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS actions_data_repository_allowed_access;",
            reverse_sql="CREATE TABLE actions_data_repository_allowed_access (id serial NOT NULL PRIMARY KEY, user_id integer NOT NULL, repository_id integer NOT NULL, source character varying(50) NOT NULL, UNIQUE (user_id, repository_id));",
        ),
    ]
