# Generated by Django 5.1 on 2024-10-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions_data", "0028_drop_repository_allowed_access_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="repositoryaccess",
            name="permissions",
            field=models.JSONField(default=dict),
        ),
    ]
