# Generated by Django 5.1 on 2024-10-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions_data", "0029_repositoryaccess_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="repositoryaccess",
            name="admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="repositoryaccess",
            name="maintain",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="repositoryaccess",
            name="pull",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="repositoryaccess",
            name="push",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="repositoryaccess",
            name="triage",
            field=models.BooleanField(default=False),
        ),
    ]
