# Generated by Django 5.1 on 2024-10-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions_data", "0031_remove_repositoryaccess_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowrun",
            name="job_data_collected",
            field=models.BooleanField(default=False),
        ),
    ]
