# Generated by Django 5.1 on 2024-10-11 09:58

import django.db.models.deletion
from django.db import migrations, models


def create_webhook_for_existing_events(apps, schema_editor):
    WebhookEvent = apps.get_model("actions_data", "WebhookEvent")
    Webhook = apps.get_model("actions_data", "Webhook")

    for event in WebhookEvent.objects.all():
        print(f"Processing event: {event}")
        webhook, created = Webhook.objects.get_or_create(
            webhook_id=event.hook_id, host=event.enterprise_host or "github.com"
        )
        event.webhook = webhook
        event.save()


class Migration(migrations.Migration):

    dependencies = [
        ("actions_data", "0032_workflowrun_job_data_collected"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhookevent",
            name="enterprise_host",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="webhookevent",
            name="enterprise_version",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="Webhook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("webhook_id", models.IntegerField()),
                ("host", models.CharField(default="github.com", max_length=255)),
            ],
            options={
                "unique_together": {("webhook_id", "host")},
            },
        ),
        # Add NULLABLE webhook field to WebhookEvent
        migrations.AddField(
            model_name="webhookevent",
            name="webhook",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="actions_data.webhook",
            ),
        ),
        # Run data migration to create Webhooks for existing WebhookEvents
        migrations.RunPython(
            create_webhook_for_existing_events, migrations.RunPython.noop
        ),
        # Make webhook field non-nullable
        migrations.AlterField(
            model_name="webhookevent",
            name="webhook",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="actions_data.webhook"
            ),
        ),
    ]
