# Generated by Django 5.1 on 2024-10-14 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_user_profiles(apps, schema_editor):
    User = apps.get_model("auth", "User")
    UserProfile = apps.get_model("actions_data", "UserProfile")

    for user in User.objects.all():
        UserProfile.objects.get_or_create(user=user)


def reverse_func(apps, schema_editor):
    # This function does nothing because deleting UserProfiles when reversing
    # this migration could lead to data loss
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("actions_data", "0033_webhookevent_enterprise_host_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("webhook_secret", models.CharField(max_length=64)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "webhooks",
                    models.ManyToManyField(blank=True, to="actions_data.webhook"),
                ),
            ],
        ),
        migrations.RunPython(create_user_profiles, reverse_func),
    ]
