# Generated by Django 5.1 on 2024-10-15 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions_data", "0034_userprofile"),
        ("social_django", "0016_alter_usersocialauth_extra_data"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="auth_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ownerentity",
            name="auth_members",
            field=models.ManyToManyField(
                related_name="organizations",
                through="actions_data.Membership",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="repository",
            name="auth_allowed_access",
            field=models.ManyToManyField(
                related_name="allowed_repositories",
                through="actions_data.RepositoryAccess",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="repositoryaccess",
            name="auth_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="ownerentity",
            name="members",
            field=models.ManyToManyField(
                related_name="social_organizations",
                through="actions_data.Membership",
                to="social_django.usersocialauth",
            ),
        ),
        migrations.AlterField(
            model_name="repository",
            name="allowed_access",
            field=models.ManyToManyField(
                related_name="social_allowed_repositories",
                through="actions_data.RepositoryAccess",
                to="social_django.usersocialauth",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="webhooks",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="actions_data.webhook"
            ),
        ),
    ]
