# Generated by Django 5.1 on 2024-10-15 11:06

from django.db import migrations

from actions_data.models import Membership, OwnerEntity


def populate_auth_user(apps, schema_editor):
    RepositoryAccess = apps.get_model("actions_data", "RepositoryAccess")
    for access in RepositoryAccess.objects.all():
        access.auth_user = access.user.user
        access.save()

    Membership = apps.get_model("actions_data", "Membership")
    for membership in Membership.objects.all():
        membership.auth_user = membership.user.user
        membership.save()


class Migration(migrations.Migration):

    dependencies = [
        ("actions_data", "0035_membership_auth_user_ownerentity_auth_members_and_more"),
    ]

    operations = [
        migrations.RunPython(populate_auth_user),
    ]
