# Generated by Django 5.1 on 2024-10-16 08:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "actions_data",
            "0038_remove_membership_user_remove_ownerentity_members_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="webhooks",
        ),
        migrations.AddField(
            model_name="webhook",
            name="users",
            field=models.ManyToManyField(
                related_name="webhooks", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
