# Generated by Django 5.1 on 2024-10-16 09:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions_data", "0039_remove_userprofile_webhooks_webhook_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhook",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
