# Generated by Django 5.1 on 2024-10-17 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions_data", "0040_webhook_created_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="userprofile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["started_at", "workflow_run_id"],
                name="actions_dat_started_3bf537_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="repositoryaccess",
            index=models.Index(
                fields=["auth_user", "repository_id"],
                name="actions_dat_auth_us_a45faa_idx",
            ),
        ),
    ]
