# Generated by Django 5.1 on 2024-10-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions_data", "0041_alter_userprofile_user_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["started_at"], name="actions_dat_started_8146f7_idx"
            ),
        ),
    ]
