# Generated by Django 5.1 on 2024-10-17 15:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions_data", "0043_job_owner_entity_job_repository_job_workflow"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="repositoryaccess",
            name="actions_dat_auth_us_a45faa_idx",
        ),
        migrations.AddIndex(
            model_name="repository",
            index=models.Index(
                fields=["id", "owner_id"], name="actions_dat_id_2c3182_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="repositoryaccess",
            index=models.Index(
                fields=["auth_user_id", "repository_id"],
                name="actions_dat_auth_us_a45faa_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workflowrun",
            index=models.Index(
                fields=["id", "repository_id"], name="actions_dat_id_f38fb4_idx"
            ),
        ),
    ]
