# Generated by Django 5.1 on 2024-10-17 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "actions_data",
            "0044_remove_repositoryaccess_actions_dat_auth_us_a45faa_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="webhooks",
            field=models.ManyToManyField(
                related_name="jobs", to="actions_data.webhook"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="workflow_run",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="actions_data.workflowrun",
            ),
        ),
    ]
