# Generated by Django 5.1 on 2024-10-17 16:11
from django.db import migrations


def populate_redundant_job_fields(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("actions_data", "0045_job_webhooks_alter_job_workflow_run"),
    ]

    operations = [
        migrations.RunPython(
            populate_redundant_job_fields, reverse_code=migrations.RunPython.noop
        ),
    ]
