# Generated by Django 5.1 on 2024-10-18 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions_data", "0046_populate_redundant_job_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField()),
                ("execution_time", models.DurationField()),
                ("billable_time", models.DurationField()),
            ],
        ),
        migrations.RemoveIndex(
            model_name="job",
            name="actions_dat_started_3bf537_idx",
        ),
        migrations.RemoveField(
            model_name="job",
            name="owner_entity",
        ),
        migrations.RemoveField(
            model_name="job",
            name="repository",
        ),
        migrations.RemoveField(
            model_name="job",
            name="webhooks",
        ),
        migrations.RemoveField(
            model_name="job",
            name="workflow",
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["workflow_run_id"], name="actions_dat_workflo_f19f79_idx"
            ),
        ),
        migrations.AddField(
            model_name="jobstats",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stats",
                to="actions_data.job",
            ),
        ),
        migrations.AddField(
            model_name="jobstats",
            name="owner_entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stats",
                to="actions_data.ownerentity",
            ),
        ),
        migrations.AddField(
            model_name="jobstats",
            name="repository",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stats",
                to="actions_data.repository",
            ),
        ),
        migrations.AddField(
            model_name="jobstats",
            name="workflow",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stats",
                to="actions_data.workflow",
            ),
        ),
        migrations.AddField(
            model_name="jobstats",
            name="workflow_run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stats",
                to="actions_data.workflowrun",
            ),
        ),
        migrations.AddIndex(
            model_name="jobstats",
            index=models.Index(
                fields=["started_at"], name="actions_dat_started_fb81fe_idx"
            ),
        ),
    ]
