# Generated by Django 5.1 on 2024-10-25 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def forward_populate_webhook_fields(apps, schema_editor):
    Webhook = apps.get_model("actions_data", "Webhook")
    WebhookEvent = apps.get_model("actions_data", "WebhookEvent")

    # For each webhook, find its first associated event and copy the target fields
    for webhook in Webhook.objects.all():
        first_event = WebhookEvent.objects.filter(webhook=webhook).first()
        if first_event:
            webhook.hook_installation_target_id = (
                first_event.hook_installation_target_id
            )
            webhook.hook_installation_target_type = (
                first_event.hook_installation_target_type
            )
            webhook.save()
        else:
            # If no associated event exists, we'll delete the webhook since the fields
            # are going to be non-nullable and we have no valid data to populate them with
            webhook.delete()


def reverse_func(apps, schema_editor):
    # No need for reverse migration as we're just populating data
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("actions_data", "0050_ownerentity_fetch_from_api_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # First add the nullable fields
        migrations.AddField(
            model_name="webhook",
            name="hook_installation_target_id",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="webhook",
            name="hook_installation_target_type",
            field=models.CharField(max_length=255, null=True),
        ),
        # Update the webhook->webhookevent relationship
        migrations.AlterField(
            model_name="webhookevent",
            name="webhook",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="actions_data.webhook",
            ),
        ),
        # Run the data migration
        migrations.RunPython(
            forward_populate_webhook_fields,
            reverse_func,
        ),
        # Now make the fields non-nullable
    ]
