# Generated by Django 5.1 on 2024-10-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions_data", "0051_webhook_hook_installation_target_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webhook",
            name="hook_installation_target_id",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="webhook",
            name="hook_installation_target_type",
            field=models.CharField(max_length=255),
        ),
        # Add the index
        migrations.AddIndex(
            model_name="webhook",
            index=models.Index(
                fields=["hook_installation_target_id", "hook_installation_target_type"],
                name="actions_dat_hook_in_dae253_idx",
            ),
        ),
    ]
