# Generated by Django 5.1 on 2024-10-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions_data", "0053_use_neutral_demo_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pullrequest",
            name="id",
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
