# Generated by Django 5.1 on 2024-10-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions_data", "0054_alter_pullrequest_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhookevent",
            name="processable",
            field=models.BooleanField(default=True),
        ),
    ]
