# Generated by Django 5.1 on 2024-10-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions_data", "0055_webhookevent_processable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflowrun",
            name="display_title",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="workflowrun",
            name="name",
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
