# Generated by Django 5.1 on 2024-11-04 10:16

from django.db import migrations
from django.db.migrations import RunPython


def remove_github_oauth_users(apps, schema_editor):
    UserSocialAuth = apps.get_model("social_django", "UserSocialAuth")
    UserSocialAuth.objects.filter(provider="github").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("actions_data", "0058_alter_job_name_alter_jobstats_billable_time_and_more"),
    ]

    operations = [RunPython(remove_github_oauth_users)]
