# Generated by Django 5.1 on 2024-11-04 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions_data", "0059_remove_github_oauth_users"),
    ]

    operations = [
        migrations.CreateModel(
            name="Installation",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        help_text="GitHub installation ID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("app_id", models.BigIntegerField(help_text="GitHub App ID")),
                ("app_slug", models.CharField(max_length=255)),
                ("client_id", models.CharField(max_length=255)),
                ("access_tokens_url", models.URLField(max_length=500)),
                ("html_url", models.URLField(max_length=500)),
                ("repositories_url", models.URLField(max_length=500)),
                ("repository_selection", models.CharField(max_length=50)),
                ("target_id", models.BigIntegerField()),
                ("target_type", models.CharField(max_length=50)),
                ("has_multiple_single_files", models.BooleanField(default=False)),
                (
                    "single_file_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("single_file_paths", models.JSONField(default=list)),
                ("events", models.JSONField(default=list)),
                ("permissions", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("suspended_at", models.DateTimeField(blank=True, null=True)),
                ("suspended_by", models.JSONField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="github_installations",
                        to="actions_data.ownerentity",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["app_id"], name="actions_dat_app_id_2c9ac2_idx"
                    ),
                    models.Index(
                        fields=["target_id"], name="actions_dat_target__6c56c4_idx"
                    ),
                ],
            },
        ),
    ]
