# Generated by Django 5.1 on 2024-11-04 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions_data", "0060_installation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="webhook",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="webhook",
            name="users",
        ),
        migrations.RemoveField(
            model_name="webhookevent",
            name="webhook",
        ),
        migrations.AddField(
            model_name="installation",
            name="enterprise_host",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="installation",
            name="installation_id",
            field=models.BigIntegerField(help_text="GitHub installation ID", null=True),
        ),
        migrations.AddField(
            model_name="installation",
            name="is_artificial",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="installation",
            name="users",
            field=models.ManyToManyField(
                related_name="installations", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="installation",
            name="webhook_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="installation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="actions_data.installation",
            ),
        ),
        migrations.AddField(
            model_name="jobstats",
            name="installation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stats",
                to="actions_data.installation",
            ),
        ),
        migrations.AddField(
            model_name="workflowrun",
            name="installation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workflow_runs",
                to="actions_data.installation",
            ),
        ),
        migrations.AlterField(
            model_name="installation",
            name="access_tokens_url",
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="installation",
            name="app_id",
            field=models.BigIntegerField(help_text="GitHub App ID", null=True),
        ),
        migrations.AlterField(
            model_name="installation",
            name="app_slug",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="installation",
            name="client_id",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="installation",
            name="created_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="installation",
            name="html_url",
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="installation",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="installation",
            name="repositories_url",
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="installation",
            name="repository_selection",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="installation",
            name="target_id",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="installation",
            name="target_type",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="installation",
            name="updated_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddConstraint(
            model_name="installation",
            constraint=models.UniqueConstraint(
                fields=("installation_id", "enterprise_host"),
                name="unique_installation_id",
            ),
        ),
        migrations.DeleteModel(
            name="Webhook",
        ),
    ]
