# Generated by Django 5.1 on 2024-11-04 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "actions_data",
            "0061_alter_webhook_unique_together_remove_webhook_users_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="installation",
            name="account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="github_installations",
                to="actions_data.ownerentity",
            ),
        ),
    ]
