# Generated by Django 5.1 on 2024-11-05 09:21

from django.db import migrations

from django.conf import settings
from django.db.migrations import RunPython


def get_or_create_demo_installation(apps, schema_editor):
    Installation = apps.get_model("actions_data", "Installation")
    Installation.objects.get_or_create(
        is_artificial=True,
        webhook_id=settings.DEMO_WEBHOOK_ID,
        installation_id=settings.DEMO_INSTALLATION_ID,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("actions_data", "0062_alter_installation_account"),
    ]

    operations = [
        RunPython(
            get_or_create_demo_installation, reverse_code=migrations.RunPython.noop
        )
    ]
