# Generated by Django 5.1 on 2024-11-05 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions_data", "0063_create_demo_installation"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhookevent",
            name="installation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="webhook_events",
                to="actions_data.installation",
            ),
        ),
    ]
