# Generated by Django 5.1 on 2024-11-05 15:33
from django.conf import settings
from django.db import migrations
from django.db.migrations import RunPython


def associate_demo_user_to_demo_installation(apps, schema_editor):
    Installation = apps.get_model("actions_data", "Installation")
    User = apps.get_model("auth", "User")
    demo_installation = Installation.objects.get(
        is_artificial=True, installation_id=settings.DEMO_INSTALLATION_ID
    )
    demo_user = User.objects.get(username=settings.DEMO_USERNAME)
    demo_installation.users.add(demo_user)


class Migration(migrations.Migration):

    dependencies = [
        ("actions_data", "0064_webhookevent_installation"),
    ]

    operations = [
        RunPython(
            associate_demo_user_to_demo_installation,
            reverse_code=migrations.RunPython.noop,
        )
    ]
