# Generated by Django 5.1 on 2024-11-05 16:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions_data", "0065_associate_demo_user_to_demo_installation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="repository",
            name="auth_allowed_access",
        ),
        migrations.AlterField(
            model_name="installation",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.DeleteModel(
            name="RepositoryAccess",
        ),
    ]
