# Generated by Django 5.1 on 2024-11-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions_data", "0066_remove_repository_auth_allowed_access_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="installation",
            name="enterprise_host",
            field=models.CharField(default="github.com", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
