# Generated by Django 5.1 on 2024-11-07 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions_data", "0067_alter_installation_enterprise_host_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RunnerCostConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "infrastructure_cost_per_hour",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Hourly cost of your runner infrastructure (if using self-hosted runners)",
                        max_digits=10,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runner_cost_config",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RunnerLabelMultiplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                (
                    "multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Cost multiplier for this runner label (e.g., 1.0 for small, 2.0 for medium)",
                        max_digits=5,
                    ),
                ),
                (
                    "cost_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="label_multipliers",
                        to="actions_data.runnercostconfig",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("cost_config", "label"),
                        name="unique_label_multiplier_per_cost_config",
                    )
                ],
            },
        ),
    ]
