# Generated by Django 5.1 on 2024-11-07 15:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions_data", "0068_runnercostconfig_runnerlabelmultiplier"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="runnercostconfig",
            name="infrastructure_cost_per_hour",
        ),
        migrations.AddField(
            model_name="jobstats",
            name="github_cost",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0"),
                help_text="Cost if run on GitHub-hosted runners",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="runnercostconfig",
            name="monthly_infrastructure_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Total monthly cost of your runner infrastructure",
                max_digits=10,
            ),
        ),
    ]
