# Generated by Django 5.1 on 2024-11-08 12:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions_data", "0071_remove_non_processable_webhook_events"),
    ]

    operations = [
        migrations.AddField(
            model_name="runnercostconfig",
            name="cost_mode",
            field=models.CharField(
                choices=[
                    ("LABEL_RATES", "Label Rates"),
                    ("OPERATIONAL_UNITS", "Operational Units"),
                ],
                default="LABEL_RATES",
                help_text="Cost calculation mode",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="runnerlabelmultiplier",
            name="per_minute_rate",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0"),
                help_text="Cost per minute for this runner label",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="runnerlabelmultiplier",
            name="multiplier",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("1"),
                help_text="Cost multiplier for this runner label (e.g., 1.0 for small, 2.0 for medium)",
                max_digits=5,
            ),
        ),
    ]
