# Generated by Django 5.1 on 2024-11-08 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("actions_data", "0072_runnercostconfig_cost_mode_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobstats",
            name="github_cost",
        ),
    ]
