# Generated by Django 5.1 on 2024-11-14 15:49

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions_data", "0073_remove_jobstats_github_cost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="runnercostconfig",
            name="monthly_infrastructure_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Total monthly cost of your runner infrastructure",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
    ]
