# Generated by Django 5.1 on 2024-11-14 15:50

from django.db import migrations
from django.db.migrations import RunPython


def add_runnercostconfig_to_all_users(apps, schema_editor):
    User = apps.get_model("auth", "User")
    RunnerCostConfig = apps.get_model("actions_data", "RunnerCostConfig")

    for user in User.objects.all():
        RunnerCostConfig.objects.get_or_create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ("actions_data", "0074_alter_runnercostconfig_monthly_infrastructure_cost"),
    ]

    operations = [
        RunPython(
            add_runnercostconfig_to_all_users, reverse_code=migrations.RunPython.noop
        )
    ]
