# Generated by Django 5.1 on 2024-11-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions_data", "0075_add_runnercostconfig_to_all_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="runnercostconfig",
            name="cost_mode",
            field=models.CharField(
                choices=[
                    ("LABEL_RATES", "Label-based Rates"),
                    ("OPERATIONAL_UNITS", "Resource-based Units"),
                ],
                default="LABEL_RATES",
                help_text="Cost calculation mode",
                max_length=20,
            ),
        ),
    ]
