# Generated by Django 5.1.3 on 2024-11-29 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("actions_data", "0076_alter_runnercostconfig_cost_mode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="runnercostconfig",
            name="cost_mode",
        ),
        migrations.RemoveField(
            model_name="runnercostconfig",
            name="monthly_infrastructure_cost",
        ),
        migrations.RemoveField(
            model_name="runnerlabelmultiplier",
            name="multiplier",
        ),
    ]
