# Generated by Django 5.1.3 on 2024-11-29 20:42

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions_data", "0077_remove_runnercostconfig_cost_mode_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="job",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["labels"], name="idx_job_labels_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="jobstats",
            index=models.Index(
                fields=["started_at", "installation_id"],
                name="actions_dat_started_8afac5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="jobstats",
            index=models.Index(
                fields=["owner_entity_id", "repository_id", "workflow_id", "job_id"],
                name="actions_dat_owner_e_c3b752_idx",
            ),
        ),
    ]
