# Generated by Django 5.1.3 on 2024-12-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions_data", "0082_jobstats_actions_dat_workflo_387c4e_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="repositories",
            field=models.ManyToManyField(
                related_name="users", to="actions_data.repository"
            ),
        ),
    ]
