# Generated by Django 5.1.3 on 2024-12-06 18:46
from django.conf import settings
from django.db import migrations
from django.db.migrations import RunPython


def create_demo_userprofile_if_not_exists(apps, schema_editor):
    UserProfile = apps.get_model("actions_data", "UserProfile")
    User = apps.get_model("auth", "User")
    demo_user, _ = User.objects.get_or_create(username=settings.DEMO_USERNAME)
    UserProfile.objects.get_or_create(user=demo_user)


class Migration(migrations.Migration):

    dependencies = [
        ("actions_data", "0083_userprofile_repositories"),
    ]

    operations = [
        RunPython(
            create_demo_userprofile_if_not_exists,
            reverse_code=migrations.RunPython.noop,
        )
    ]
