# Generated by Django 5.1.3 on 2024-12-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions_data", "0084_add_demo_userprofile_if_not_exists"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="jobstats",
            index=models.Index(
                fields=["repository_id", "started_at"],
                name="actions_dat_reposit_a2e680_idx",
            ),
        ),
    ]
