# Generated by Django 5.1.3 on 2024-12-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions_data", "0085_jobstats_actions_dat_reposit_a2e680_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobstats",
            name="event",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
