# Generated by Django 5.1.3 on 2024-12-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions_data", "0086_jobstats_event"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="jobstats",
            index=models.Index(fields=["event"], name="actions_dat_event_317ae4_idx"),
        ),
        migrations.AddIndex(
            model_name="jobstats",
            index=models.Index(
                fields=["workflow_run_id"], name="actions_dat_workflo_f5b0a0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="runnerlabelmultiplier",
            index=models.Index(
                fields=["cost_config_id", "label"],
                name="actions_dat_cost_co_22af0d_idx",
            ),
        ),
    ]
