# Generated by Django 5.1.3 on 2024-12-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions_data", "0087_jobstats_actions_dat_event_317ae4_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="jobstats",
            index=models.Index(
                fields=["repository_id", "started_at", "event"],
                name="actions_dat_reposit_ecf586_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="jobstats",
            index=models.Index(
                fields=["billable_time"], name="actions_dat_billabl_589051_idx"
            ),
        ),
    ]
