# Generated by Django 5.1.3 on 2024-12-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions_data", "0088_jobstats_actions_dat_reposit_ecf586_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="repository",
            index=models.Index(
                fields=["owner_id", "name"], name="actions_dat_owner_i_d480b6_idx"
            ),
        ),
    ]
