# Generated by Django 5.1.3 on 2024-12-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions_data", "0089_repository_actions_dat_owner_i_d480b6_idx"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="jobstats",
            index=models.Index(
                fields=[
                    "owner_entity_id",
                    "repository_id",
                    "workflow_id",
                    "job_id",
                    "started_at",
                ],
                name="actions_dat_owner_e_ca201c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="runnerlabelmultiplier",
            index=models.Index(
                fields=["cost_config_id", "label", "-per_minute_rate"],
                name="actions_dat_cost_co_d07f2d_idx",
            ),
        ),
    ]
