# Generated by Django 5.1.3 on 2024-12-12 14:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "actions_data",
            "0092_runnercostconfig_actions_dat_user_id_6dc6b6_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="runnercostconfig",
            index=models.Index(
                fields=["user_id", "id"], name="actions_dat_user_id_68f356_idx"
            ),
        ),
    ]
