# Generated by Django 5.1.3 on 2024-12-12 21:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions_data", "0093_runnercostconfig_actions_dat_user_id_68f356_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="ownerentity",
            name="actions_dat_login_7bf484_idx",
        ),
        migrations.AddIndex(
            model_name="jobstats",
            index=models.Index(
                fields=["repository_id", "owner_entity_id", "started_at"],
                name="actions_dat_reposit_ac97cf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="jobstats",
            index=models.Index(
                fields=["execution_time"], name="actions_dat_executi_1511e3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ownerentity",
            index=models.Index(
                fields=["login"], include=("id",), name="idx_ownerentity_login_id"
            ),
        ),
    ]
