# Generated by Django 5.1.3 on 2024-12-12 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "actions_data",
            "0094_remove_ownerentity_actions_dat_login_7bf484_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="jobstats",
            name="job_name",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="jobstats",
            name="owner_entity_name",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="jobstats",
            name="repository_name",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="jobstats",
            name="workflow_name",
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
