name: Pre-commit Hooks

on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize ]


jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install pre-commit
        run: pip install -r requirements.txt -r requirements-ci.txt

      - name: Run pre-commit hooks
        run: pre-commit run --all-files
        env:
          GITHUB_APP_PRIVATE_KEY: 'fakekey'
          MAIN_URL: 'https://buildbudget.test'
